# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_auto_20170812_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorscore',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.Mentor'),
        ),
    ]
