# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 06:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_auto_20170812_0611'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mentorscore',
            unique_together=set([('activity', 'mentor')]),
        ),
    ]
