# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0005_auto_20170812_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='mentorteam',
            name='team_name',
            field=models.CharField(max_length=250, verbose_name='Name of Team'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
