# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 02:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0007_auto_20170812_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='date_of_performance',
            field=models.DateField(default=datetime.date(2017, 8, 14)),
            preserve_default=False,
        ),
    ]
