# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 21:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0011_auto_20170815_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorscore',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL),
        ),
    ]
