# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('C', 'Candidate'), ('M', 'Mentor'), ('A', 'Admin')], default='C', max_length=1, verbose_name='Type of User'),
        ),
    ]
