# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170815_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='show.MentorTeam'),
            preserve_default=False,
        ),
    ]
